name: 'Delete-Issue'
description: 'The Github action allowing you to delete issues from the repo'
author: 'vtcaregorodtcev'
branding:
  icon: delete
  color: black
inputs:
  github_token:
    description: 'The GitHub token used to create an authenticated client'
    required: true
  issue_number:
    description: 'Issue to delete'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
